#!/bin/bash

# generates three comparative visualizations from data 
# elsewhere in the repository from lists of files and 
# labels in filelistcb and filelistsz

plotkmerspectrum.py -l filelistcv -g 1 -w png  # makes filelistcv.1.png
plotkmerspectrum.py -l filelistsz -g 5 -w png  # makes filelistsz.5.png
plotkmerspectrum.py -l filelistsz -g 6 -w png  # makes filelistsz.6.png

# SRR006330.fastq.21.fit.png is generated by test/test-kmerspectrumanalyzer.sh
