#!/bin/bash

# generates three comparative visualizations from data 
# elsewhere in the repository from lists of files and 
# labels in filelistcb and filelistsz

plotkmerspectrum.py -l filelistcv -g 1 -w png  # makes filelistcv.1.png
plotkmerspectrum.py -l filelistsz -g 5 -w png  # makes filelistsz.5.png
plotkmerspectrum.py -l filelistsz -g 6 -w png  # makes filelistsz.6.png

plotkmerspectrum.py -l filelistcv -g 1 -w eps  # makes filelistcv.1.eps
plotkmerspectrum.py -l filelistsz -g 5 -w eps  # makes filelistsz.5.eps
plotkmerspectrum.py -l filelistsz -g 6 -w eps  # makes filelistsz.6.eps

plotkmerspectrum.py -l filelistcv -g 1 -w pdf  # makes filelistcv.1.pdf
plotkmerspectrum.py -l filelistsz -g 5 -w pdf  # makes filelistsz.5.pdf
plotkmerspectrum.py -l filelistsz -g 6 -w pdf  # makes filelistsz.6.pdf

# SRR006330.fastq.21.fit.png is generated by test/test-kmerspectrumanalyzer.sh
